import styles from "./page.module.css"
import Image from "next/image"
import Link from "next/link";


export const metadata = {
  title: `Hexa Shop - products`,
  description: 'Generated by create next app',
}

async function getData() {
  const res = await fetch('https://dummyjson.com/products')


  if (!res.ok) {

    throw new Error('Failed to fetch data')
  }

  return res.json()
}

export default async function product() {

  const data = await getData()
  const products=data.products

  return (
    <div className={styles.mainContainer}>
      {products.map(product => (
<Link key={product.id} href={`/product/${product.id}`}className={styles.post}>
        <div className={styles.imageContainer}>
          <Image src={product.thumbnail}
            fill={true} className={styles.image} alt="Eslam Reda image" />
</div>
          <div className={styles.content}>
            <h1 className={styles.title}>{product.title}</h1>
            <p className={styles.text}> {product.description}</p>
          </div>

      </Link>
      ))}














    </div>
  )
}
