import Navbar from '@/Components/Navbar/Navbar'
import './globals.css'
import { Montserrat } from 'next/font/google'

import Footer from '@/Components/Footer/Footer'
import { ThemeProvider } from '@/Context/Themecontext'



const bodyfont = Montserrat({ subsets: ['latin'], weight: ['400', '900', '700'] })


export const metadata = {
    title: 'Hexa Shop',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
    return ( <
        html lang = "en" >

        <
        body className = { bodyfont.className } >
        <
        ThemeProvider >
        <
        div className = "container" >
        <
        Navbar / >

        { children } <
        Footer / >
        <
        /div> <
        /ThemeProvider>

        <
        /body> <
        /html>
    )
}